access_token = '0b53967b-2448-4338-9148-58d971da3da6'
device_id = '60d3ad1d-0a88-434e-88b4-cd497448f7b2'
license_key = '085M9sbd-5VpJ6j43-5mW7h69K'
private_key = 'qC0fWY5cT2D7S0oVRrTOCE7H/udMdQipnTGW+Nax0k0='
