access_token = '374be7bc-8fe2-4c11-a0e1-577c29394776'
device_id = 'e8c4ec85-5010-4883-bc57-e7615270c786'
license_key = '2yQ83Ld5-41wq6B3b-086sUG4d'
private_key = '6FMlUN6tNyXebYZWZBtIBX5hZYiv8c7HG0ggw5KNM1E='
