access_token = '00464efa-f704-4804-b2f2-27935d85d817'
device_id = '61efc23d-ad4f-4427-837b-1a19b2cb48bf'
license_key = '6rC9vM25-A14JU03b-16wU80YM'
private_key = 'IHtq7JolvW1Z0f0XRsws2wcCEDNug+5TMNBBKXHyZmI='
