access_token = 'af2a7aaa-20ef-4076-ac78-06ab93eb12b6'
device_id = '6e3becd9-1aa7-499c-8238-af7e7435f599'
license_key = '40Oi9VA7-6K9jn5m0-3Vb5sL19'
private_key = 'eO7v/wPwU0PekFTeLBF4D2WRt3lPwj0NNVS+v/JE52s='
