access_token = 'e45dc954-9e90-45f0-b40e-394dcbfcd051'
device_id = '1942547b-6571-4414-8b5a-ebb062958c29'
license_key = '0sB3k72T-82ulS4c3-7RX4g85u'
private_key = 'OB0DQaAFOKnHZ4/3j85FeAu7znsyKzzfNohvdR/Ro1E='
