access_token = 'a0b1cd39-aecb-4ef2-8d67-f9fa5972cc32'
device_id = '32cc228a-ac48-47a0-84b8-3a5baf716cb2'
license_key = 'S9I37T6E-Y6VH930k-b86kp1d0'
private_key = 'gGTkgH4ovXjfoKlq/Qur4vuH3JmsrnQA/4+rRfHIIXE='
