access_token = '8974538e-53f2-4547-8f39-1104bcb7fc5a'
device_id = '93d7afc0-3b84-48cc-b72b-cd604382bb41'
license_key = 'Ug9Sb763-26n0c7vW-6yZ5g3f1'
private_key = 'wEpSWxwdcJ3zPyJlnG4N+73BGXUGvpcXoF40MhhDpFU='
