access_token = '4ddbd963-9f2f-4777-81a6-f87ebc76c530'
device_id = '4b77c79d-e60d-49cf-88be-9fe6fdd9441a'
license_key = '6zD93uw7-89rYUy46-S93k0Jv2'
private_key = 'aExgseaGQDrd8n69f90N4owzrUCaxYuZeHwfL8MNL0Q='
