access_token = '546e3924-24b7-461f-b1ff-03f88c42b4a7'
device_id = 'e1a9770b-5cdd-4949-afc5-4a68f74f0c6d'
license_key = 'zV9142dR-JTC3y476-P9B2c1a4'
private_key = 'IP3BTp6dR649/oPIulpoKVwcBD5teEAStFI7V3tBXF8='
