access_token = '302fbd92-3f86-43df-a929-117d78fc2b3f'
device_id = '1f07b12e-f3d9-4662-abb1-a0bc3cb3d807'
license_key = '4z2t6Zs7-48F79Lht-23Ih18mA'
private_key = '8C3vZx1ZeWq8ECAgKl54RNrfueZpV/voa/afT20xy2k='
