access_token = 'b3b7b6de-dc97-4a41-b945-2982a9e0429d'
device_id = '06f597ae-8930-4006-a588-87a4a82cddb4'
license_key = 'a4U7my09-WE9J04e6-8c5bR3H9'
private_key = 'GJ6h9k472iIWePFdlTBdZQNd0yvsoJw525fN9YVgi2s='
