access_token = '8744a939-0568-4181-9655-0b3d89f792a9'
device_id = '512c7f15-e35a-48c2-bd2e-7a7fc59dbc6a'
license_key = '52V8sL3W-Ji8ua359-uL5K182B'
private_key = 'iIRCRNfBYcINKK0UhyKxXfHELI2QxqWXKg4cKBjYEG0='
