access_token = '1b83159a-aa0b-4481-a286-0ed1cc758cfc'
device_id = '09142547-9384-4a63-8bc0-b5f47575abc7'
license_key = 'r9YK027f-24TH8o3m-14oJ3An2'
private_key = 'IFcKze4Me7yZzrI6kkXQN69pLWcLGN7bjanW/8BZxGY='
