access_token = 'f4a915d2-9c66-4ac3-836e-2a8cfda21882'
device_id = 'f12c5672-c1d2-444b-b16b-30835dda6394'
license_key = '2I76n9OS-U80M2W1R-27uz0hl5'
private_key = 'gF5GPPTAqXOWOs/TEmGEPCQreyJ+/COiDNG9slo0j18='
