access_token = '05b8a2bb-4fd4-4bb4-9765-51ec5ec7ee57'
device_id = '9e586e1a-a554-41f6-8a14-71695f4cbeea'
license_key = '130ISN8Q-IB0a275d-2x3o6ub9'
private_key = 'SGXxG7C9/cOCHuggQ351ID3cGKPMOHM2t/czD1US6m8='
