access_token = '74d12a61-c49d-4658-a102-81c11b08198c'
device_id = '02b071c4-fce3-4153-a76a-7b311206918f'
license_key = '03l8b7PB-F71O36VW-r58q37Ou'
private_key = 'cAGRhebj/pe6nwQxfOaU580YgIgAw18ahDswLcyX5U0='
