access_token = '6f4d1653-eae9-409e-961a-57909f3dac37'
device_id = '8442ddba-f392-407a-96ae-9e9dc70a277d'
license_key = 'H293dE1m-EHs6872e-0c7MpV21'
private_key = 'yJseNwQod4FK+8uJj4kFr7OJt6qPfKMph0sSZNj2sVg='
