access_token = '987ec44a-2bec-4222-bf55-614c7760058e'
device_id = '859864c8-f5e9-4b6d-95b7-47e4e02f23a9'
license_key = '68f24Vru-uE0x7q13-cnt6130k'
private_key = 'YAA0zndz3rRQy32ZdyKrtTCvmokrvLY4SWPJ/rZsGk4='
