access_token = '072a8ae7-78dc-4059-a4b3-82e364be3976'
device_id = 'dc1b23a0-16cf-4298-8af6-5c62c9573800'
license_key = 'c5U603Qt-NS4r986X-Uj821QD4'
private_key = 'CGnWP5QDjnpvJAnPh9dR5bnLeLMDOH3nW9sLPnt3PU8='
