access_token = 'ffad5219-1323-4979-882e-b43f92f72814'
device_id = '35dce7ab-011d-4837-a353-c9a6b9c5e119'
license_key = '0X2ps47w-42A0IS8L-HtMT7304'
private_key = 'yPpj1wRgcgggEViG3Faag6S6webU18DRIywaC+fdHn8='
