access_token = '5a1d73bf-e3db-4a88-8e41-1225c863694f'
device_id = '49f25a0b-c003-4dc0-8c69-16a19cacaa6e'
license_key = '89e53dfj-o938m7MH-j26o8u0l'
private_key = 'MB9tlGc+DScgdO1ZpTBNUPs3rTwI5ELNH/wYm3ylrUw='
